HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.history

#source $XDG_CONFIG_HOME/user-dirs.dirs
alias ...='../..' 
alias ....='../../..' 
alias .....='../../../..' 
alias ......='../../../../..' 
alias .......='../../../../../..'

fpath=($fpath $HOME/.zsh/func)
typeset -U fpath

PATH=$PATH:/Users/jkkulick/anaconda3/bin
