#
# User configuration sourced by interactive shells
#

# Change default zim location 
export ZIM_HOME=${ZDOTDIR:-${HOME}}/.zim

# Source zim
if [[ -s ${ZIM_HOME}/init.zsh ]]; then
  source ${ZIM_HOME}/init.zsh
fi
# .zshrc
# author: Johannes Kulick

# aliases {{{
alias ll="ls -lh"
alias la="ls -lah"
alias vi="vim"
alias ssha="ssh-add /home/johannes/.ssh/id_rsa"
alias make="make -j 4"
alias tmux="TERM=screen-256color-bce tmux"
alias groovy="source ~/src/catkin_ws/devel/setup.zsh"
alias addpr2="source ~/SparkleShare/mlr\ documents/doc/pr2/pr2lansetup"
alias ipnb="ipython2 notebook"

alias mlr="cd /home/johannes/mlr"
alias nmn="notmuch new"
#}}}

bindkey "^[[1~" beginning-of-line
bindkey "^[[4~" end-of-line


# directory stack {{{
export DIRSTACKSIZE=16
setopt autopushd pushdminus pushdsilent pushdtohome
alias dh="dirs -v"
# }}}

#use wx for gnuplot
export GNUTERM=wxt


# Add RVM to PATH for scripting. Make sure this is the last PATH variable change.
export PATH="$PATH:$HOME/.rvm/bin"
